# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b-SgoXvcUm80xbgjlBgc8GiAYIvsp7XC
"""

!pip install numpy

import numpy as np

numpydizisi = np.array([1,2,3,4,5])

print(numpydizisi)

print(type(numpydizisi))

benimlistem = [23,52,62]

print(type(benimlistem))

np.array(benimlistem)

matrisListesi = [[10,20,30],[20,3,40],[30,40,50]]

print(matrisListesi[1][1])

np.array(matrisListesi)

np.__version__

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])

